  name: RadisBot

  # Controls when the action will run. Triggers the workflow on pull request
  # events but only for the master branch
  on: [pull_request]

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Python Syntax Checker
        uses: clauss/Find-Python-syntax-errors-action@v0.2.0
      - uses: Black Code Formatter
        run: lgeiger/black-action@v1.0.1