  name: RadisBot

  # Controls when the action will run. Triggers the workflow on pull request
  # events but only for the master branch
  on: [pull_request]

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Pyflakes Syntax Checker
        uses: lgeiger/pyflakes-action@v1.0.1
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1