  name: RadisCI

  # Controls when the action will run. Triggers the workflow on push or pull request
  # events but only for the master branch
  on: [pull_request]

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        run: lgeiger/black-action@v1.0.1
      - name: Python Syntax Checker
        run: clauss/Find-Python-syntax-errors-action@v0.2.0

